### ISSUE TITLE
[Usage Problem] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by bigcyy** [YunYouJun/hexo-theme-starry#292]
- 主题版本号： v1.9.1
- 今天git clone master仓库主题后执行hexo clean出现SyntaxError: Cannot use import statement outside a module。
  - 截图
![image](https://user-images.githubusercontent.com/73413979/168209993-8f28a472-17d4-4fac-adea-9fa6b4de345e.png)

**Comment by YunYouJun** [comment]
[迁移指南](https://yun.yunyoujun.cn/guide/migrate.html)

1.8 版本以后已改为使用 npm 安装。
