### ISSUE TITLE
[Bug Report]引用的js无法正确识别路径

### ISSUE THREAD

**Issue by BnqDzj** [YunYouJun/hexo-theme-starry#299]
**Describe the bug**
在head的base处添加引用 https://hk1.monika.love/PipecraftNet/jsdelivr-auto-fallback/main/index.min.js 时生成的html去请求了/h /t /t /p /s 等
![QQ截图20220522145148](https://user-images.githubusercontent.com/64721413/169682783-54f6d1e6-dd90-44af-b862-46d3913f6b4a.png)

**To Reproduce**
在_config.yun.yml中配置
head:
  css:
  js:
    base: https://hk1.monika.love/PipecraftNet/jsdelivr-auto-fallback/main/index.min.js
    async:

**Expected behavior**
应该去请求 https://hk1.monika.love/PipecraftNet/jsdelivr-auto-fallback/main/index.min.js 而不是去请求/h /t /t /p /s 等路径

**Screenshots**
![QQ截图20220522145148](https://user-images.githubusercontent.com/64721413/169682783-54f6d1e6-dd90-44af-b862-46d3913f6b4a.png)
生成的html
![QQ截图20220522145738](https://user-images.githubusercontent.com/64721413/169682970-8a9d5cd4-ded3-4242-8c99-ad1df70d67df.png)

**Desktop (please complete the following information):**

- OS: Windows 11+ Node.js v18.2.0
- Browser Microsoft Edge 103.0.1255.0
- Version "hexo": "^6.1.0" "hexo-theme-yun": "^1.9.3"

**Comment by YunYouJun** [comment]
You should use it like this:

```yml
head:
    js:
      base:
        - xxx

# not base: xxx
```
