### ISSUE TITLE
[Bug Report] utterances 在 Android Chrome 中不能正常显示

### ISSUE THREAD

**Issue by sakimidare** [YunYouJun/hexo-theme-starry#301]
**Bug 描述**
如题，Android Chrome 中不能正常显示utterances，而其他浏览器（如vivo浏览器）可以正常显示（见下图）

**复现**
未经测试，不保证在其他浏览器（或不同配置的 Chrome）中能够复现。

**截图**
1. Chrome 版本
[![OzDXRI.md.jpg](https://s1.ax1x.com/2022/05/22/OzDXRI.md.jpg)](https://imgtu.com/i/OzDXRI)
2. vivo 浏览器中的显示效果
[![OzDjzt.md.jpg](https://s1.ax1x.com/2022/05/22/OzDjzt.md.jpg)](https://imgtu.com/i/OzDjzt)
3. Chrome 中的显示效果
[![OzDxQP.md.jpg](https://s1.ax1x.com/2022/05/22/OzDxQP.md.jpg)](https://imgtu.com/i/OzDxQP)
4. Chrome - 设置 - 网站设置 中的配置
[![OzDOJA.md.jpg](https://s1.ax1x.com/2022/05/22/OzDOJA.md.jpg)](https://imgtu.com/i/OzDOJA)

**关于设备**

- 设备: vivo y93（v1818a）
- OS: Android 8.1.0
- 浏览器版本: Chrome 70.0.3538.110
- Hexo 版本: 
```shell
$ hexo --version
INFO  Validating config
INFO  Yun version 1.9.1. Guide: https://yun.yunyoujun.cn
hexo: 6.2.0
hexo-cli: 4.3.0
os: android 4.9.82-perf+
node: 17.9.0
v8: 9.6.180.15-node.16
uv: 1.43.0
zlib: 1.2.12
brotli: 1.0.9
ares: 1.18.1
modules: 102
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 3.0.2
cldr: 41.0
icu: 71.1
tz: 2022a
unicode: 14.0
```

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/hexo-theme-yun/blob/dev/packages/hexo-theme-yun/layout/_third-party/comments/utterances.pug

这是 utterances 的所有设置，均采用 CDN，因此我不认为这和主题有关。

utterances 由于基于 GitHub，往往无法在国内拥有良好的访问性，因此我认为可能这单纯由网络状况导致（譬如浏览器缓存了 DNS、原生浏览器走了代理等）。
可以再试一下别的（

**Comment by sakimidare** [comment]
> https://github.com/YunYouJun/hexo-theme-yun/blob/dev/packages/hexo-theme-yun/layout/_third-party/comments/utterances.pug
> 
> 这是 utterances 的所有设置，均采用 CDN，因此我不认为这和主题有关。
> 
> utterances 由于基于 GitHub，往往无法在国内拥有良好的访问性，因此我认为可能这单纯由网络状况导致（譬如浏览器缓存了 DNS、原生浏览器走了代理等）。
> 可以再试一下别的（

好的，我试试（（（

（顺便说一下，我只是个初三狗，所以github不常上，有些回复可能看不到，敬请谅解）

**Comment by YunYouJun** [comment]
先关闭 Issue 了，如果确定和主题有关可以重新开启。
