### ISSUE TITLE
[Feature Request]希望能增加文档图片放大的功能

### ISSUE THREAD

**Issue by Poteato0** [YunYouJun/hexo-theme-starry#303]
如题，目前已查阅您的配置教程文档，并未发现此功能。
我认为对于一些教程类网站常常需要增添一些“信息量较大”的图片，而又不想改变页面图片大小，希望能点击图片实现放大
电脑端通过网址访问图片原地址的确可以实现放大，但较为繁琐，且手机操作更为不便
在此对您致谢，希望能够实现此功能

**Comment by YunYouJun** [comment]
https://user-images.githubusercontent.com/25154432/170550468-de8bb48f-b542-4590-b4df-e46ad70d155c.mov


我添加了 `medium-zoom` 来放大预览图片。

可以通过如下方式在 `_config.yun.yml` 中开启：

```yml
medium_zoom: true
```

Released in v1.10.2.
