### ISSUE TITLE
yun主题下七牛云图片无法显示

### ISSUE THREAD

**Issue by 61hhh** [YunYouJun/hexo-theme-starry#307]
您需要提供的内容：

- 主题版本号（必须）： v1.8.11
- 您遇到的问题（必须）： 七牛云图片无法显示，换成默认的landscape主题就可以显示了，检查过markdown语法应该是没问题的。
  - 线上yun主题：
![image](https://user-images.githubusercontent.com/36224650/170855460-695449af-3928-49c0-a005-92271a7e3f82.png)
  - 本地hexo s，landscape主题：
![image](https://user-images.githubusercontent.com/36224650/170855479-733f3ce9-ee1f-4f26-8d1b-8db84722ceef.png)
- 本地typora格式：
![image](https://user-images.githubusercontent.com/36224650/170855498-16a0269a-db7c-456d-a35c-5ae44135d8f7.png)

**Comment by YunYouJun** [comment]
请提供可复现页面和图片地址。

**Comment by 61hhh** [comment]
博客地址：
https://salute61.top/20220528/ea10fc6a/
图片地址：
http://img2.salute61.top/MD/image-20220328101230533.png
目前所有七牛云图床的图片在yun主题下都有同样的问题，测试用github图床可以正常显示

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/170984677-48e6de12-3a5d-496b-8262-1fb4b48f9971.png)

页面无法访问。

我不认为这和主题有关，这通常由防盗链导致。
而本地 localhost 不会触发防盗链规则。

**Comment by 61hhh** [comment]
我在浏览器中可以访问：
![image](https://user-images.githubusercontent.com/36224650/171088042-dcffbf0d-b62f-401a-aa0e-c39e9e542e67.png)
至于防盗链问题，之前有检查过，我的七牛云存储空间没有开启防盗链设置，空间也是公开空间：
![image](https://user-images.githubusercontent.com/36224650/171088193-333b2e9d-6aa6-4f09-b141-190f41c256ac.png)
可能是个例问题吧。。后续图片统一迁移到GitHub上

**Comment by YunYouJun** [comment]
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/25154432/171146671-b00eb707-cbc6-4c0c-9f07-b6e073183162.png">

测试本地主题图片正常显示，只能是防盗链的原因了。其他无法复现。
