### ISSUE TITLE
代码区域  手机不兼容

### ISSUE THREAD

**Issue by zhao-yang857** [YunYouJun/hexo-theme-starry#313]
您需要提供的内容：

- 主题版本号（必须）： v1.3.0
- 您遇到的问题（必须）： 手机上代码块超出 没有横向滚动条。

- 您期待的结果（必须）：我希望能够得到您的回复。
- 您所尝试的操作（可选）：我尝试了复制你的一篇博客的源码，但是 还是不行。我在想是不是我博客有问题，我就想再重新配置下主题，我是用的之前clone的方式  自动创建theme文件夹  现在看到你新的下载方式 我有点不知道怎么办了，用把theme文件夹删掉吗，然后参考您哪个步骤呢

**Comment by YunYouJun** [comment]
见文档迁移指南，升级到最新版本。
