### ISSUE TITLE
[Feature Request]能否将github的提交记录嵌入到主页

### ISSUE THREAD

**Issue by Poteato0** [YunYouJun/hexo-theme-starry#317]
云游好！能否实现一个类似[这个博客](https://blog.falling42.top/)主页的效果，将github的提交记录嵌入到主页呢？
不太清楚这个是butterfly主题配置带的的还是自己加的
当然貌似这个功能好像只是好看，如果实现比较麻烦的话就算了，谢谢辛苦了！

**Comment by Poteato0** [comment]
另外上次在QQ频道里反映的那个奇怪的报错，是我自己的原因吗？（感觉最近也没调整什么东西的说）

**Comment by YunYouJun** [comment]
这个功能感觉可以自制插件实现，不必作为主题内置。

问题请详细说明，并通过 Issue 反馈。
