### ISSUE TITLE
[Feature Request] 图标自定义

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/hexo-theme-starry#319]
如题。我想把 Remix Icon 改成 Fluent Design Icon 时注意到部分图标无法进行更改（如返回顶部按钮、文章内的标签图标与分类图标、LeanCloud Visitor 图标等）

是否有什么方法更改上面列出的图标？

**Comment by YunYouJun** [comment]
暂未支持替换，Todo。

**Comment by YunYouJun** [comment]
Released in `v1.10.5`.
