### ISSUE TITLE
[Usage Problem]从1.7.0更新至1.10.4后，图标无法显示

### ISSUE THREAD

**Issue by krau** [YunYouJun/hexo-theme-starry#320]
- 主题版本号： v1.10.4
- 您遇到的问题： 社交图标、主页、分类、tag图标无法显示的问题
  - 截图
  - 
![图片](https://user-images.githubusercontent.com/71133316/174477163-30d20b35-706f-4904-b61d-04a5d0f516d9.png)
  - 线上预览地址https://krau.top
- 您期待的结果（必须）：我希望能够使这些图标正确显示。

**Comment by YunYouJun** [comment]
`v1.10` 之后的版本使用 iconify 加载图标，尝试检查你的配置是否使用这种格式。

https://github.com/YunYouJun/hexo-theme-yun/blob/80f41e677f744806ebb42b718b77d4740b3880b9/packages/hexo-theme-yun/_config.yml#L140

> https://yun.yunyoujun.cn/guide/migrate.html#%E8%BF%81%E7%A7%BB%E8%87%B3-v1-11-%E4%B9%8B%E5%90%8E%E7%9A%84%E7%89%88%E6%9C%AC

**Comment by krau** [comment]
> `v1.10` 之后的版本使用 iconify 加载图标，尝试检查你的配置是否使用这种格式。
> 
> https://github.com/YunYouJun/hexo-theme-yun/blob/80f41e677f744806ebb42b718b77d4740b3880b9/packages/hexo-theme-yun/_config.yml#L140
> 
> > https://yun.yunyoujun.cn/guide/migrate.html#%E8%BF%81%E7%A7%BB%E8%87%B3-v1-11-%E4%B9%8B%E5%90%8E%E7%9A%84%E7%89%88%E6%9C%AC

感谢回复！照此配置后得到解决。
