### ISSUE TITLE
[Feature Request] Theme provide HMR

### ISSUE THREAD

**Issue by bigbigDreamer** [YunYouJun/hexo-theme-starry#321]
如题，是否可以在 `hexo-theme-yun` 的 `hexo` 主题中内置 `live reload`.

可以内置一个 `deps`, [hexo-browsersync](https://github.com/hexojs/hexo-browsersync) 就足够了。

**Comment by YunYouJun** [comment]
`hexo-browsersync` 应当由用户自行安装，这部分内容不应该由主题来做。

以及 hexo 并不支持局部的 HMR，这也是我开发 [Valaxy](https://github.com/YunYouJun/valaxy) 的原因之一。

**Comment by bigbigDreamer** [comment]
Agree～
