### ISSUE TITLE
[Feature Request]底部备案号能支持添加公安网备案信息吗？

### ISSUE THREAD

**Issue by ilovn** [YunYouJun/hexo-theme-starry#329]
格式：备案编号图标在前，备案编号在后，如本网站底部格式。
```
<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=XXXXXXXX" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="" style="float:left;"/><p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">京公网安备 XXXXXXXX号</p></a>

```

**Comment by YunYouJun** [comment]
尝试 `footer.custom_text` 是否满足需求？

公安网备案我没有，所以没有尝试过。

**Comment by ilovn** [comment]
素材我可以提供支持，除了刚才的代码，还有一个图标就行，目前国内站似乎都要做公安备案了。

**Comment by YunYouJun** [comment]
图标是否有公共的 CDN 链接？
以及示例？

**Comment by ilovn** [comment]
![](https://pic.zy.hn/u/O_rcrGM1d)
图标没有cdn资源,代码格式,其中image标签需要自己填上自己存放图标的地址:
`<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=XXXXXXXX" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="" style="float:left;"/><p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">京公网安备 XXXXXXXX号</p></a>`

**Comment by YunYouJun** [comment]
公网安备一定都是北京的吗？

**Comment by YunYouJun** [comment]
<img width="237" alt="截屏2022-07-25 23 25 30" src="https://user-images.githubusercontent.com/25154432/180815886-99435eb2-d866-4e81-93e8-ce60dea056a7.png">

Added.

**Comment by YunYouJun** [comment]
Will be released in `v1.10.6`.
