### ISSUE TITLE
[Usage Problem]

### ISSUE THREAD

**Issue by ricardowangyf** [YunYouJun/hexo-theme-starry#330]
大佬你好，今天我在使用您主题的时候想把它部署到线上，但是发现左边栏里的icon社交图标全都不见了，但是本地又能显示，请问这是什么原因？
![image](https://user-images.githubusercontent.com/81006817/180611792-9eb1603c-5920-43d5-ab54-98f1127b3bff.png)
![image](https://user-images.githubusercontent.com/81006817/180611802-8ca1a185-06a5-4f93-a398-4d44b86fdd3e.png)

**Comment by YunYouJun** [comment]
请提供可复现地址，并检查版本是否一致等。

**Comment by ricardowangyf** [comment]
谢谢大佬，已经搞定了，好像是我CDN没有部署进去。。。
