### ISSUE TITLE
[Bug Report] Reward的icon实际上无法自定义

### ISSUE THREAD

**Issue by boxie123** [YunYouJun/hexo-theme-starry#331]
**Describe the bug**
在[文档](https://yun.yunyoujun.cn/guide/config.html#%E6%89%93%E8%B5%8F)中，reward可自定义icon，但实际上，在 `hexo-theme-yun/packages/hexo-theme-yun/layout/_partial/post/reward.pug` 中，直接写为：
```javascript
+icon('ri:hand-coin-line')
```
并未读取自定义的icon内容。

> Yun version 1.10.5.

**Comment by boxie123** [comment]
另外建议文档添加关于`reward.methods.link`的说明(๑•̀ㅂ•́)و✧

**Comment by YunYouJun** [comment]
感谢反馈，已修复。
