### ISSUE TITLE
[Feature Request] 增加对 umami 访问统计的支持

### ISSUE THREAD

**Issue by chitang233** [YunYouJun/hexo-theme-starry#332]
**Is your feature request related to a problem? Please describe.**
[umami](https://github.com/umami-software/umami) 是在 <head> 中添加一个 js 进行加载，但需要传入一个参数
yun 只能选择加载方式而无法传入参数

**Describe the solution you'd like**
增加对 [umami](https://github.com/umami-software/umami) 的支持或允许用户在添加自定义 js 时传参

**Comment by YunYouJun** [comment]
I haven't used it, and I don't know how to add parameters.
Do you want to create a PR for it?

**Comment by chitang233** [comment]
No, I can't write themes

**Comment by asadahimeka** [comment]
@chitang233  , You can use hexo(version > 5) [injector](https://hexo.io/zh-cn/api/injector) to insert the script tag like this: 

```js
// <blog_root>/scripts/injector.js
hexo.extend.injector.register('head_end', '<script async defer data-website-id="<your-website-id>" src="<your-umami-url>"></script>');
```
Then you can [track events](https://umami.is/docs/track-events) using CSS classes or Javascript

For example:

```html
<button id="signup-button" class="button umami--click--signup-button">Sign up</button>
```

```js
// in your custom js
function addUmamiClickEvent(sel, name) {
  const el = document.querySelector(sel);
  el && el.addEventListener('click', () => {
    window.umami(name);
  });
}
addUmamiClickEvent('#search', 'click search btn');
```

**Comment by chitang233** [comment]
> 

Thanks, that's quite useful!
