### ISSUE TITLE
[Feature Request] 希望可以修改底部文本间的间距，目前版本的间距不太合理及美观

### ISSUE THREAD

**Issue by akiting01** [YunYouJun/hexo-theme-starry#341]
如题，目前版本（1.10.6）的底部footer的间距有点不太美观，底部custom_text与上部文本及下部support之间的间距过紧。  
![](https://s1.328888.xyz/2022/08/24/wjGCX.png)  
不知道是否为我的使用方式有误还是其他的原因，希望作者您可以做出修改，谢谢！

**Comment by YunYouJun** [comment]
`custom_text` 默认没有间距，这样用户可以自行决定间距（`style=""`）。

> 譬如倘若 `custom_text` 自带 `margin`，那么用户很难自定义缩减。

**Comment by akiting01** [comment]
好的，谢谢解答！  
那么我想自定义间距是否只需更改`footer.styl`文件就可以了呢？（没有接触过hexo主题文件，还望云游君解答，十分感谢）

**Comment by YunYouJun** [comment]
如果你指的是主题源文件，那么不建议修改。
你可以外挂 `xxx.styl` 来书写自己的 CSS 样式即可，它会覆盖默认的样式。

**Comment by akiting01** [comment]
好的，谢谢解答
