### ISSUE TITLE
[Bug Report] 已为 LeanCloud Visitors 功能指定 server_url，但仍使用国际版公共 API

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/hexo-theme-starry#345]
**Describe the bug**
由于 LeanCloud 国际版 API 限制了国内用户请求，因此我在 `server_url` 中填写了我绑定的 API 域名。但是在 DevTools 中发现 LeanCloud Visitors 走的还是国际版的公共 API。

文档中的示例也是这样填写的

![image](https://user-images.githubusercontent.com/76810494/187392437-bb299d00-1215-4d2e-ac1d-e2bae17386ea.jpeg)

无论是我自己的站点还是云游君自己的站点都是一样的情况。

**To Reproduce**

1. 使用 LeanCloud 国际版
2. 指定 `server_url`
3. 打开站点

**Expected behavior**
`server_url` 的值应该正确处理，LeanCloud Visitors 应该正确显示

**Screenshots**
![image](https://user-images.githubusercontent.com/76810494/187393529-6a356cb8-eb11-412a-9ae0-72782da05ec8.jpeg)
![image](https://user-images.githubusercontent.com/76810494/187393591-7bc78bee-9a10-4a3d-9660-8f107e04ba18.jpeg)
![image](https://user-images.githubusercontent.com/76810494/187393625-aa7ae260-1e04-4cdf-a0fd-ca792fe82fd4.jpeg)
![image](https://user-images.githubusercontent.com/76810494/187393643-534cfe21-82f4-4e30-888b-a746074d8442.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS: iOS 16 Public Beta (Latest build)
- Browser: Safari
- Version 16 (WebKit 605.1.15)

**Comment by YunYouJun** [comment]
appID 以 `-MdYXbMMI` 结尾的始终会走国际版，你的应用是否创建于国际版下？

**Comment by Big-Cake-jpg** [comment]
> appID 以 `-MdYXbMMI` 结尾的始终会走国际版，你的应用是否创建于国际版下？

是国际版应用

**Comment by YunYouJun** [comment]
那其实是没有区别的（应该）。

**Comment by Big-Cake-jpg** [comment]
> 那其实是没有区别的（应该）。

btw 指定了`server_url`还走国际版公共 API欸，不应该在获取到这个值以后直接用这个吗，这个是已经在 LeanCloud 控制台里绑定的域名

**Comment by YunYouJun** [comment]
这里是故意做了判断逻辑，当以 `-MdYXbMMI` 结尾，使用国际公共域名。

Emm，可以考虑移除。
