### ISSUE TITLE
[Bug Report]隐藏文章导致的每页文章数量不一致，并出现某一页无文章的情况

### ISSUE THREAD

**Issue by krau** [YunYouJun/hexo-theme-starry#346]
**Describe the bug**
如题。我的博客网站：https://krau.top

因为我隐藏的文章数较多，在[第一页](https://krau.top)显示了七篇文章，而在[第二页](https://krau.top/page/2/)显示了六篇文章，在[第三页](https://krau.top/page/3/)甚至没有文章显示。

希望云游君能抽空改进一下这个问题。

（我的博客访问可能较慢，所以下方附上问题最明显的第三页的截图）

**Screenshots**
![图片](https://user-images.githubusercontent.com/71133316/187428701-a1630098-5774-46f9-9249-e7934e5c2b21.png)

**Comment by YunYouJun** [comment]
由于涉及到上游 [hexo-pagination](https://github.com/hexojs/hexo-pagination)、[hexo-generator-index](https://github.com/hexojs/hexo-generator-index) 等插件的策略，主题层面暂时无法进行修改。

可选方案1：将需要隐藏的文章移动至 `source/_posts` 之外的文件夹，如 `source/xxx`。

可选方案2：我正在尝试构建 [Valaxy](https://github.com/YunYouJun/valaxy) 以解决目前 Hexo 存在的一些问题（如配置热更新、组件化等），如果时间充裕可以考虑切换，将会很快添加该功能。

**Comment by krau** [comment]
了解，感谢回复
