### ISSUE TITLE
不显示Post文章的标题怎么改…之前乱搞弄没了

### ISSUE THREAD

**Issue by Lowlowlowlowlowlow** [YunYouJun/hexo-theme-starry#347]
像这样，那个框可以点开，内容正常，就是不显示标题

![1663495119709](https://user-images.githubusercontent.com/49236618/190896568-79b7e1a7-5067-4e17-bcce-7db82c7ca9bc.jpg)

**Comment by YunYouJun** [comment]
```md
---
title: xxx
---
```
