### ISSUE TITLE
[Usage Problem]怎么设置默认深色

### ISSUE THREAD

**Issue by Ezgx** [YunYouJun/hexo-theme-starry#350]
# 怎么设置默认为深色模式？
```problem
怎么设置默认为深色模式？
```

**Comment by YunYouJun** [comment]
`_config.yun.yml`

```yaml
mode: dark
```

> https://yun.yunyoujun.cn/guide/config.html#%E4%BA%AE%E6%9A%97%E6%A8%A1%E5%BC%8F
