### ISSUE TITLE
[Usage Problem]warn no layout index.html

### ISSUE THREAD

**Issue by Ezgx** [YunYouJun/hexo-theme-starry#351]
![image](https://user-images.githubusercontent.com/110729988/193240116-a780cd27-ad45-470e-bf03-88aac57c558d.png)

**Comment by YunYouJun** [comment]
检查是否安装渲染器。

> https://yun.yunyoujun.cn/guide/#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
