### ISSUE TITLE
[Usage Problem]严重问题导致无法使用

### ISSUE THREAD

**Issue by Ezgx** [YunYouJun/hexo-theme-starry#352]
![image](https://user-images.githubusercontent.com/110729988/193241395-5a30999f-e90e-47d0-954d-f1c554718714.png)
![image](https://user-images.githubusercontent.com/110729988/193241492-005f9631-c1cf-4c51-a20e-e43ea7ae18cb.png)
![image](https://user-images.githubusercontent.com/110729988/193241553-635a0430-758f-464e-8a2e-8f8e9c939e02.png)

**Comment by YunYouJun** [comment]
#351
