### ISSUE TITLE
[Usage Problem]

### ISSUE THREAD

**Issue by ghost** [YunYouJun/hexo-theme-starry#362]
我要如何更改这里的内容
![image](https://user-images.githubusercontent.com/115859505/196017696-471aeaf5-e34c-450f-8f6c-d5416872061f.png)

**Comment by ghost** [comment]
@YunYouJun

**Comment by Ezgx** [comment]
> 我要如何更改这里的内容
> ![image](https://user-images.githubusercontent.com/115859505/196017696-471aeaf5-e34c-450f-8f6c-d5416872061f.png)

# Yun.yunyoujun.cn

**Comment by Ezgx** [comment]
> @YunYouJun

_config.yml里面改
里面找到云游君的小站，改成自己想要的的就行了
这里推荐用vscode编辑，可以搜索指定内容
## 注意这里说的是主题的_config.yml而不是博客根目录的
[hexo博客](https://wlopck.gitee.io)

**Comment by YunYouJun** [comment]
博客根目录下新建 _config.yun.yml，覆盖 `banner.title`。参见文档。

> https://yun.yunyoujun.cn/guide/config.html#%E6%A0%87%E8%AF%AD%E5%8A%A8%E7%94%BB
