### ISSUE TITLE
[Bug Report] 使用 `head` 引用的 `js` 掺杂着 `HTML` 标签

### ISSUE THREAD

**Issue by FoliageOwO** [YunYouJun/hexo-theme-starry#369]
如题, 使用 `head` 引用的 `js` 最后都会掺杂着一些不该出现的 `HTML` 标签,
![image1](https://user-images.githubusercontent.com/58383985/204103689-d53ddb0d-182f-4529-af2b-b5e52f1dc2bb.png)

并且在控制台会报错,
![image2](https://user-images.githubusercontent.com/58383985/204104044-f2ea9207-94a5-4dfd-a69a-7b63bc356dc5.png)

但我的 `js` 文件只有一行输出,
![image3](https://user-images.githubusercontent.com/58383985/204103725-5e8ab4aa-77f6-4bdc-812e-c08870dc8879.png)

`_config.yun.yml` 设置的 `head` 如图:
![image4](https://user-images.githubusercontent.com/58383985/204104061-1a0f1b74-409c-45aa-bfa6-0017302f42dd.png)

**Comment by WindLeaf233** [comment]
这个是我朋友的博客, 完整的 `_config.yun.yml` 配置 [在这里](https://github.com/NiuFuyu855/HexoActions/blob/main/_config.yun.yml)

**Comment by FoliageOwO** [comment]
经测试, 发现是 `hexo` 误以为 `source/js` 这个目录是一个 `Page`, 所以才会把 `js` 文件的内容加上 `HTML` 标签:
![image1](https://user-images.githubusercontent.com/58383985/204136523-7c71db01-9ac1-44bf-9fb5-182d44df8e86.png)

---

官网文档是这样写的, 是文档出了什么问题, 或者哪里配置不对?
![image2](https://user-images.githubusercontent.com/58383985/204136725-ade3e135-76b8-47f0-a3b1-14ec5cc492d8.png)

**Comment by YunYouJun** [comment]
对，这个有个坑，可以通过设置 `exclude` folders 来解决。

参见：https://hexo.io/docs/configuration#Include-x2F-Exclude-Files-or-Folders

考虑提交 PR 补充文档吗？

**Comment by FoliageOwO** [comment]
好的, 谢谢!

> 考虑提交 PR 补充文档吗？

等会我有空的时候会提 pr, 我会按照标准写文档

再次感谢百忙中解答

**Comment by NiuFuyu855** [comment]
云游君考虑出一期 Hexo 迁移 Valaxy 的教程吗？
不会迁移（
Valaxy 的文档也看了，没找到（

**Comment by YunYouJun** [comment]
收到邮件了，但是评论怎么没了（

<img width="375" alt="image" src="https://user-images.githubusercontent.com/25154432/204141989-014e20ee-f29d-40dd-96e0-a31fa893e5d7.png">

Valaxy 正在活跃维护更新中。
我想根据实际用户遇到的痛点需求来写，你在迁移的时候遇到什么困惑吗？
我可以直接协助你迁移。

**Comment by NiuFuyu855** [comment]
> 收到邮件了，但是评论怎么没了（
> 
> <img alt="image" width="375" src="https://user-images.githubusercontent.com/25154432/204141989-014e20ee-f29d-40dd-96e0-a31fa893e5d7.png">
> 
> Valaxy 正在活跃维护更新中。 我想根据实际用户遇到的痛点需求来写，你在迁移的时候遇到什么困惑吗？ 我可以直接协助你迁移。

刚刚我朋友 @WindLeaf233 建议我不要直接在这里问，与此话题不相干，完全可以去 [Valaxy](https://github.com/YunYouJun/valaxy/issues) 那里提 issue，我想想也对，就删了

Valaxy 迁移工作我目前还没有进行，只是想找找有没有教程可以帮我~~避雷~~更快地完成迁移

我先试试吧，就不麻烦您了，有问题再问您吧！

**Comment by FoliageOwO** [comment]
@YunYouJun 大佬, 直接使用 `exclude` 是不行的

直接 `exclude` 会导致访问 `js/xxx.js` 返回 **`404`** 错误

我看到有人使用 `skip_render` 解决了这个问题, 我使用这个办法也解决了

![image](https://user-images.githubusercontent.com/58383985/204152226-3d882389-0860-4307-a9b8-872b56ca98a1.png)

那文档的注意项应该是写 `exclude` 还是 `skip_render`?

**Comment by YunYouJun** [comment]
对，就是 `skip_render`。我给忘了，随便搜了下给粘了个 `exclude`，抱歉。

**Comment by FoliageOwO** [comment]
> 对，就是 `skip_render`。我给忘了，随便搜了下给粘了个 `exclude`，抱歉。

@YunYouJun 已经发 pr 了, 如果有写的不妥的地方希望可以 change request 指教
