### ISSUE TITLE
[Bug Report]默认的社交图标不显示了？

### ISSUE THREAD

**Issue by YunMengs** [YunYouJun/hexo-theme-starry#375]
为了不影响，我重新建了一个hexo，然后npm安装了主题，发现默认的社交图标不显示了......但是去云游君的博客看了看，是有的，不过他的图标好像没看到svg标签.
那默认图标是新更新的时候去掉了吗？

**Comment by YunMengs** [comment]
补充：
1. 去掉了所有浏览器插件，不是插件的问题
2. 重新新建了一个hexo博客，并安装了新版主题

**Comment by YunYouJun** [comment]
图标采用了新的命名方式，并不再需要提供默认图标。

图标会根据名称按需加载。

https://yun.yunyoujun.cn/guide/config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87
