### ISSUE TITLE
关于代码高亮主题的设置

### ISSUE THREAD

**Issue by mewhz** [YunYouJun/hexo-theme-starry#380]
您需要提供的内容：

- 主题版本号（必须）： v1.10.9
- 您遇到的问题（必须）： 我遇到了 无法设置代码高亮主题的问题。
- 您期待的结果（必须）：我希望能够得到 代码高亮主题的 结果。
- 您所尝试的操作（可选）：我尝试了 修改不同的主题内容，但是 并没有效果。

您所提供的内容越详细，越能够尽快得到你想要的解答。
您好，我是从低版本迁移过来，当时还是yun.yml 配置文件，迁移成功后发现代码高亮的主题无法修改，我按照文档尝试了两种配置方法，但是没有效果，以下两个配置是分别在根目录下的_config.yun.yml文件中进行配置
![image](https://user-images.githubusercontent.com/48837161/227120972-a99bdd12-6fba-4ae0-9838-213c36552268.png)
![image](https://user-images.githubusercontent.com/48837161/227121474-0d76116d-eb77-4219-9722-b1fce075ed0f.png)
最后依然是这个效果的代码高亮
![image](https://user-images.githubusercontent.com/48837161/227121571-39702150-7748-42cc-ab9c-647d940a031c.png)

感谢您的回复

**Comment by 112567** [comment]
请问你解决了吗？我也遇到这个问题

**Comment by mewhz** [comment]
> 

我也还没解决，不知道该怎么办

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/227832324-33b5a13c-0bcf-4137-9b72-3869a3ab4268.png)

您好，`v1.8.3` 之后废弃了自定义代码样式主题的功能。

https://github.com/YunYouJun/hexo-theme-yun/blob/6a5a3d9255dbea681293491898e383dba249bb01/docs/guide/config.md?plain=1#L1116-L1117

该部分使用了 CSS Var 的方式实现，因此用户可以覆盖定制每一区块的色彩，但无法再复用已有的 CDN 主题。

**Comment by YunYouJun** [comment]
另一方面 `hexo-theme-yun` 已进入维护模式，将不会再进行功能性的修改。

因此推荐使用 [valaxy](https://github.com/YunYouJun/valaxy) 及 valaxy-theme-yun，valaxy-theme-yun 已复刻了 hexo-theme-yun 的几乎所有功能，并在速度上进行了一些优化，并可直接使用。具体可参见我的博客 [yunyoujun.cn](https://www.yunyoujun.cn/) 已实装。

---

hexo-theme-yun 由于过于静态模版的特性，大量使用了第三方 CDN（如 jsdelivr），但随着 jsdelivr 在国内失去备案丧失了部分可访问性，强依赖公共 CDN 的方案已经不再占优。
valaxy 的实现通过打包的方式实现了本地的静态化，按需引入。

在代码主题方面则改为了 shiki 实现，相比 prismjs，shiki 可以实现与 vscode 完全适配的主题，以及预编译后更优的性能。

**Comment by mewhz** [comment]
> 另一方`hexo-theme-yun`已经进入维护模式，将不会再进入功能性的修改。
> 
> 因此推荐使用[valaxy](https://github.com/YunYouJun/valaxy)及valaxy-theme-yun，valaxy-theme-yun 已经复刻了hexo-theme-yun 的几乎所有功能，并且正在速度上进行了一些优化，并且可以直接接入我的应用程序。[yunyoujun.cn](https://www.yunyoujun.cn/)已实装。
> 
> hexo-theme-yun由于由于模版的特性 valaxy 的实际通过打包的方式实际发现了本地的静态化，需要引入。
> 
> 在代号主题方面则改为了 shiki 实现，相比 prismjs，shiki 可以实现与 vscode 完全适合配置的主题，以及预测编译后更好的性能。

非常感谢您的回复，我已经下载了 valaxy 引擎并重新进行配置~
