### ISSUE TITLE
[Bug Report] 加密相册页面生成的 Open Graph `<meta>` 标签会泄露图片的实际链接

### ISSUE THREAD

**Issue by asadahimeka** [YunYouJun/hexo-theme-starry#382]
**Describe the bug**
加密相册生成的 HTML 文件中将相册图片的实际链接生成为`<meta property="og:image" >`  标签，会导致加密图片泄露

**To Reproduce**

1. 前往 https://hexo-theme-yun.yunyoujun.cn/albums/sunset
2. 右键查看页面源代码
3. 搜索 `<meta property="og:image"`
4. 可看到图片链接

**Expected behavior**
加密相册页面不应生成相关的 OG 标签

**Screenshots**

![image](https://github.com/YunYouJun/hexo-theme-yun/assets/31837214/3949c993-7bdd-433e-913a-d3e1cc9d6643)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Microsoft Edge
- Version: 117.0.2045.36

**Comment by YunYouJun** [comment]
Will fix it asap.
