### ISSUE TITLE
[Usage Problem]在文章内容中写入一些Bash内置变量会导致后面的内容被截断

### ISSUE THREAD

**Issue by watanabe-hsad** [YunYouJun/hexo-theme-starry#398]
以下是我提出来的一些存在问题的内容
![](https://github.com/YunYouJun/hexo-theme-yun/assets/120468183/feb5eb84-c2e4-4056-b2c9-15cfe6a6ee67)

在本地测试发现反引号中间内容可以正常显示，但是在尝试把第三行内容用反引号包起来依旧会截断后面内容
![image](https://github.com/YunYouJun/hexo-theme-yun/assets/120468183/0bfa6d3f-6da4-4bfe-83c8-c0cf45fd0cb7)

![image](https://github.com/YunYouJun/hexo-theme-yun/assets/120468183/f498c26b-ded7-4324-b45c-a99c96548138)
后面再添加任何信息都不会显示

**Comment by YunYouJun** [comment]
如果你正在使用 hexo，该问题很可能由 hexo-browsersync 导致。

> 见 https://yun.yunyoujun.cn/guide/faq.html#hexo-server-%E6%96%87%E7%AB%A0%E5%8F%AA%E6%B8%B2%E6%9F%93%E9%83%A8%E5%88%86%E5%86%85%E5%AE%B9

我强烈推荐您迁移至 https://github.com/YunYouJun/valaxy
